name: Build ParticleMod

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Build Starting Notification
        run: |
          echo "Thanks to Conor for the build file!"
          COMMIT_DESCRIPTION=$(git log --pretty=format:"%s by %an (%D)" -n 1)
      - name: Download JDK 1.8 # actions/setup-java@v1 doesn't download it correctly, so we download it manually and pass the file to setup-java
        run: |
          wget -O jdk.tar.gz https://cdn.azul.com/zulu/bin/zulu8.40.0.25-ca-jdk8.0.222-linux_x64.tar.gz -o /dev/null
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          jdkFile: jdk.tar.gz
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build Success Notification
        run: |
          COMMIT_DESCRIPTION=$(git log --pretty=format:"%s by %an (%D)" -n 1)
